Repository pyupio/dparse, pull requests merged in 2023-10, with the labels that each got.

#73 Run tests on PR events
  .github/workflows/main.yml
Labels: ci

#69 replace ConfigParser's 'readfp' by 'read_string'
  dparse/parser.py
Labels: enhancement

#74 Trigger label check on fork PRs
  .github/workflows/pr-labels.yml
Labels: ci

#68 Add pyproject.toml parser
  README.rst
  dparse/dependencies.py
  dparse/filetypes.py
  dparse/parser.py
  tests/test_parse.py
Labels: new-feature

#66 Support poetry.lock version >= 1.5
  dparse/parser.py
  tests/test_parse.py
Labels: bugfix

#75 ci(.github): revamp workflows and add hatch
  .github/workflows/ci.yml
  .github/workflows/code_analysis.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .pre-commit-config.yaml
  conftest.py
  dparse/dependencies.py
  dparse/parser.py
  dparse/updater.py
  hatch.toml
  pyproject.toml
  tests/test_dependencies.py
  tests/test_parse.py
  tests/test_updater.py
Labels: ci

#76 perf(.github): prepare release workflows
  .github/workflows/ci.yml
  .github/workflows/release.yml
  hatch.toml
Labels: performance

#77 perf(pyproject.toml): Set the start version of the new dparse release
  hatch.toml
  pyproject.toml
Labels: ci, performance
